### ISSUE TITLE
Add hierachical clustering and config adjustment

### ISSUE THREAD

**Issue by pz-max** [pz-max/pypsa-africa#404]
## Describe the feature you'd like to see

PyPSA-Eur recently implemented hierarchical clustering ("hac") options as an alternative to kmeans. The commit gives some hints what scripts need to be adjusted: https://github.com/PyPSA/pypsa-eur/commit/f9a996e5df758f28364d8906baf35ee3f101d7b3 but the implementation should happen according to the PyPSA-Eur repository since multiple changes happened after the original commit:
https://github.com/PyPSA/pypsa-eur/blob/44e8fbd5aa846ee47a4b0ee1ae7350cb8fc4da9c/config.default.yaml#L235-L252

Article from @martacki about clustering approaches: "A comparison of clustering methods for the spatial reduction of renewable electricity optimisation models of Europe" https://energyinformatics.springeropen.com/articles/10.1186/s42162-022-00187-7

The to-be-developed config could look like:
```
cluster_options:
  out_logging: true  # When true, logging is printed to console
  alternative_clustering: false  # "False" use Voronoi shapes, "True" use GADM shapes
  distribute_cluster: ['load'] # ['load'],['pop'] or ['gdp']
  simplify_network:
    algorithm: kmeans # choose from: [hac, kmeans]
    feature: solar+onwind-time # only for hac. choose from: [solar+onwind-time, solar+onwind-cap, solar-time, solar-cap, solar+offwind-cap] etc.
  cluster_network:
    algorithm: kmeans
    feature: solar+onwind-time
  aggregation_strategies:
    generators:
      p_nom_max: sum # use "min" for more conservative assumptions
      p_nom_min: sum
      p_min_pu: mean
      marginal_cost: mean
      committable: any
      ramp_limit_up: max
      ramp_limit_down: max
      efficiency: mean
```
